### ISSUE TITLE
Изменить язык по-умолчанию

### ISSUE THREAD

**Issue by blazern** [blazern/VeganCheck#15]
Язык по-умолчанию должен быть английский, потому что приложение доступно для скачивания ото всюду, но пользователь из какой-нибудь Африки скорее знает не русский, а английский.

**Comment by ZEUSKanekiKen** [comment]
а как изменить себе язык а то я не пойму что здесь делать?

**Comment by blazern** [comment]
Как изменить язык в VeganCheck'е?
Это обычное приложение под Андроид - в приложениях под Андроид язык меняется тогда, когда пользователь телефона меняет язык ОС в настройках ОС.
